services:
  auth-service:
    build: ./backend/auth_service
    ports:
      - "8001:8001"
    environment:
      - APP_ENV=development
      - APP_PORT=8001
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@auth-db:5432/auth_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRY_MINUTES=30
    depends_on:
      auth-db:
        condition: service_healthy

  qa-service:
    build: ./backend/qa_service
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - APP_PORT=8000
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@qa-db:5432/qa_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      qa-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  qa-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=qa_db
    volumes:
      - qa_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
  qa_db_data:
